import hashlib
import subprocess
import sys
from importlib.metadata import version

import pytest
from rich.text import Text
from typer.testing import CliRunner

from dvc_data.cli import app


def run_cli(*args):
    return subprocess.run(  # noqa: S603 - arguments are generated by these tests
        [sys.executable, "-m", "dvc_data", *args],
        capture_output=True,
        text=True,
        check=False,
    )


@pytest.mark.parametrize("args", [("--version",), ("--version", "hash")])
def test_version(args):
    result = run_cli(*args)
    assert result.returncode == 0, result.stderr
    assert result.stdout.strip() == f"dvc-data, version {version('dvc-data')}"


@pytest.mark.parametrize("force_color", [False, True])
def test_help(monkeypatch, force_color):
    monkeypatch.delenv("NO_COLOR", raising=False)
    monkeypatch.delenv("FORCE_COLOR", raising=False)
    monkeypatch.setenv("TERM", "xterm")
    if force_color:
        monkeypatch.setenv("FORCE_COLOR", "1")
    result = run_cli("--help")
    assert result.returncode == 0, result.stderr
    help_text = Text.from_ansi(result.stdout).plain
    assert "--version" in help_text
    assert "hash" in help_text


def test_hash(tmp_path):
    path = tmp_path / "data"
    data = b"CLI compatibility\n"
    path.write_bytes(data)
    in_process = CliRunner().invoke(app, ["hash", str(path)])
    assert in_process.exit_code == 0, in_process.output
    result = run_cli("hash", str(path))
    assert in_process.stdout == result.stdout
    assert result.returncode == 0, result.stderr
    assert (
        result.stdout.strip()
        == f"md5: {hashlib.md5(data, usedforsecurity=False).hexdigest()}"
    )


def test_version_in_process():
    result = CliRunner().invoke(app, ["--version"])
    assert result.exit_code == 0, result.output
    assert result.stdout.strip() == f"dvc-data, version {version('dvc-data')}"
